### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by belidi** [pilotak/homeassistant-clientraw#8]
Afetre update of HASS, i have this error :Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/clientraw/sensor.py", line 92, in async_setup_platform
    await weather.async_update()
  File "/config/custom_components/clientraw/sensor.py", line 363, in async_update
    temperature = float(self.data[47])
ValueError: could not convert string to float: '-

No value at the sensor

**Comment by pilotak** [comment]
could you please post you configuration? and also the url so can test it

**Comment by belidi** [comment]
- platform: clientraw
    url:  https://www.bel1.eu/meteo/uploadMH/clientraw.txt
    interval: 5
    monitored_conditions:
        - temp
        - heat_index
        - humidex
        - temp_day_min
        - temp_day_max 
        - wind_degrees
        - temp_indoor
        - wind_dir
        - wind_gust_hour
        - wind_gust_day
        - wind_speed
        - pressure
        - humidity
        - humidity_indoor
        - cloud_height
        - forecast
        - daily_rain
        - monthly_rain
        - yearly_rain
        - rain_rate

**Comment by belidi** [comment]
Core 2021.2.2
Supervisor 2021.02.9
OS 5.11

**Comment by belidi** [comment]
System Health

version: core-2021.2.3
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 5.4.83-v8
arch: aarch64
timezone: Europe/Brussels


GitHub API: ok
Github API Calls Remaining: 4785
Installed Version: 1.11.3
Stage: running
Available Repositories: 749
Installed Repositories: 4


logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


host_os: Home Assistant OS 5.11
update_channel: stable
supervisor_version: supervisor-2021.02.9
docker_version: 19.03.13
disk_total: 14.1 GB
disk_used: 2.3 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), Terminal & SSH (9.0.1), File editor (5.2.0)


dashboards: 1
resources: 0
views: 2
mode: storage

**Comment by pilotak** [comment]
In your clientraw file, there is no such a info about
- temp_day_min
- temp_day_max
- wind_gust_hour
- wind_gust_day

i will send a patch, when such a value is not available it will become unavailable in HA

**Comment by pilotak** [comment]
I believe this is now fixed. Feel free to reopen if any problem occurs

**Comment by belidi** [comment]
hello, after restarting, it still doesn’t work here is what I got as Logger error: homeassistant.components.sensor
  Source: custom_components / clientraw / sensor.py: 354
  Integration: Sensor (documentation, problems)
  First appearance: 10:14:40 (1 occurrences)
  Last login: 10:14:40

  Error configuring the clientraw platform for the sensor
  Traceback (most recent last call):
    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
      wait asyncio.shield (task)
    File "/config/custom_components/clientraw/sensor.py", line 92, in async_setup_platform
      wait for the weather forecast. async_update ()
    File "/config/custom_components/clientraw/sensor.py", line 354, in async_update
      temperature = float (self.data [46])
  ValueError: cannot convert string to float: '-'

Envoyé de mon iPad

**Comment by pilotak** [comment]
Have you upgraded the component manually by downloading is from github?

**Comment by belidi** [comment]
no, i uninstalled and reinstalled via hacs integration.

**Comment by belidi** [comment]
Ok, it's the same result via manual installation ( GitHub)

**Comment by pilotak** [comment]
please post you error again. I have tried it with you config above and it works without error

**Comment by belidi** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/clientraw/sensor.py:205 
Integration: Capteur (documentation, issues) 
First occurred: 26 février 2021 à 18:15:25 (1 occurrences) 
Last logged: 26 février 2021 à 18:15:25

Error while setting up clientraw platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/clientraw/sensor.py", line 95, in async_setup_platform
    await weather.async_update()
  File "/config/custom_components/clientraw/sensor.py", line 205, in async_update
    new_state = int(self.data[48])
ValueError: invalid literal for int() with base 10: '-'

**Comment by pilotak** [comment]
Ok so you changed the configuration and added `symbol` which i didn't cover in the fix.

I have pushed an update, could you please get the latest version from github and try it? if this is succesfull i will release it to HACS

**Comment by belidi** [comment]
Ok, well it works, I have no more errors in the log and my data has reappeared. Thank you very much for your investment

**Comment by belidi** [comment]
sorry, but after a few hours of operation, i still have errors (without making any changes to the systems).  Logger: custom_components.clientraw.sensor
 Source: custom_components / clientraw / sensor.py: 171
 Integration: clientraw (documentation, issues)
 First occurred: 9:25:02 (1 occurrences)
 Last logged: 9:25:02

 Will try again shortly: https://www.bel1.eu/meteo/uploadMH/clientraw.txt returned 502
 Logger: homeassistant
 Source: custom_components / clientraw / sensor.py: 190
 First occurred: 3:48:52 (9 occurrences)
 Last logged: 8:00:01

 Error doing job: Task exception was never retrieved
 Traceback (most recent call last):
 ile "/config/custom_components/clientraw/sensor.py", line 190, in async_update
 ease ValueError ('Could not parse the file')
 ValueError: Could not parse the file

Envoyé de mon iPad

**Comment by pilotak** [comment]
This is a your server error nothing to do with this component. If the server doesn't give me data i can't parse them
